# coding: utf-8

"""
    Sample API

    A sample API for testing OpenAPI specifications

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_items_get(self) -> None:
        """Test case for items_get

        Get all items
        """
        pass

    def test_items_item_id_get(self) -> None:
        """Test case for items_item_id_get

        Get item by ID
        """
        pass

    def test_items_item_id_put(self) -> None:
        """Test case for items_item_id_put

        Update an item
        """
        pass

    def test_items_post(self) -> None:
        """Test case for items_post

        Create a new item
        """
        pass


if __name__ == '__main__':
    unittest.main()
