# coding: utf-8

"""
    Sample API

    A sample API for testing OpenAPI specifications

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.items_post_request import ItemsPostRequest

class TestItemsPostRequest(unittest.TestCase):
    """ItemsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemsPostRequest:
        """Test ItemsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemsPostRequest`
        """
        model = ItemsPostRequest()
        if include_optional:
            return ItemsPostRequest(
                name = ''
            )
        else:
            return ItemsPostRequest(
                name = '',
        )
        """

    def testItemsPostRequest(self):
        """Test ItemsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
